apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: garbage-collection-example
    app.kubernetes.io/part-of: garbage-collection-example
    app.kubernetes.io/managed-by: kustomize
  name: example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: garbage-collection-example
    app.kubernetes.io/part-of: garbage-collection-example
    app.kubernetes.io/managed-by: kustomize
  name: garbage-example
  namespace: example
